on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: arekinath/thing:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: ./deploy.sh
        env:
          DOCKER_CA: ${{secrets.DOCKER_CA}}
          DOCKER_KEY: ${{secrets.DOCKER_KEY}}
          DOCKER_CERT: ${{secrets.DOCKER_CERT}}
          DOCKER_HOST: ${{secrets.DOCKER_HOST}}
